# use Ganache's forked mainnet mode as the default network
# NOTE: You don't *have* to do this, but it is often helpful for testing
networks:
  default: mainnet-fork

# exclude SafeMath when calculating test coverage
# https://eth-brownie.readthedocs.io/en/v1.10.3/config.html#exclude_paths
reports:
  exclude_contracts:
    - SafeMath

dependencies:
  - alphachainio/chainlink-contracts@1.1.2

compiler:
  solc:
    #     # Don't set a compiler version since there are multiple solc versions in the
    #     # codebase and brownie will handle them via the pragma statements.
    #     version: 0.6.6
    remappings:
      - '@chainlink=alphachainio/chainlink-contracts@1.1.2'
# automatically fetch contract sources from Etherscan
# TODO: leave commented out for hackathon
# autofetch_sources: True

